// lib/errors/codes.ts
export const ErrorCodes = {
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_VALIDATION_FAILED: 'AI_VALIDATION_FAILED',
  AI_RATE_LIMIT: 'AI_RATE_LIMIT',
  AI_TIMEOUT: 'AI_TIMEOUT',
  NOT_BASKETBALL_COURT: 'NOT_BASKETBALL_COURT',
  NO_PEOPLE_DETECTED: 'NO_PEOPLE_DETECTED',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  INAPPROPRIATE_CONTENT: 'INAPPROPRIATE_CONTENT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
