export const ErrorCodes = {
  // Validación (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_FIELD: 'MISSING_FIELD',

  // Autenticación (401)
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Autorización (403)
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Not Found (404)
  NOT_FOUND: 'NOT_FOUND',
  COMMUNITY_NOT_FOUND: 'COMMUNITY_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Conflictos (409)
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  PENDING_CONTRIBUTION: 'PENDING_CONTRIBUTION',

  // Reglas de negocio (422)
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  AI_VALIDATION_FAILED: 'AI_VALIDATION_FAILED',
  LOCATION_TOO_CLOSE: 'LOCATION_TOO_CLOSE',

  // Errores externos (502/503)
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  GEMINI_ERROR: 'GEMINI_ERROR',
  STORAGE_ERROR: 'STORAGE_ERROR',

  // Errores internos (500)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
